Jupyter console 6.0.0

Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.



[?1l[6n[?2004h[?25l[0m[?7l[0m[J[0;38;5;28mIn [[0;38;5;46;1m1[0;38;5;28m]: [0m                                                                                                                            [132C [8C[?7h[0m[?12l[?25h[?25l[?7l[8D[0;38;5;28mIn [[0;38;5;46;1m1[0;38;5;28m]: [0mpip install matplotlib [0m[K[0m
[0;38;5;28m      : [0m                                                                                                                            [132C [8C[?7h[0m[?12l[?25h[?25l[?7l[?7h[0m[?12l[?25h[?25l[?7l[A[8D[0m[J[0;38;5;28mIn [[0;38;5;46;1m1[0;38;5;28m]: [0mpip install matplotlib [0m
[0;38;5;28m      : [0m                                                                                                                            [132C [0m
[J[?7h[0m[?12l[?25h[?2004lException in default exception handler
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/posix.py", line 155, in _run_task
    t()
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/context.py", line 116, in new_func
    return func(*a, **kw)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/patch_stdout.py", line 103, in write_and_flush_in_loop
    run_in_terminal(write_and_flush, in_executor=False)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/run_in_terminal.py", line 50, in run_in_terminal
    return run_coroutine_in_terminal(async_func, render_cli_done=render_cli_done)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/run_in_terminal.py", line 71, in run_coroutine_in_terminal
    assert app._is_running
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/base.py", line 132, in call_exception_handler
    self._exception_handler(context)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/application.py", line 729, in handle_exception
    run_coroutine_in_terminal(print_exception)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/application/run_in_terminal.py", line 71, in run_coroutine_in_terminal
    assert app._is_running
AssertionError
Requirement already satisfied: matplotlib in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (3.5.1)
Requirement already satisfied: fonttools>=4.22.0 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: cycler>=0.10 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: python-dateutil>=2.7 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (21.3)
Requirement already satisfied: numpy>=1.17 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (1.22.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from matplotlib) (1.4.2)
Requirement already satisfied: six>=1.5 in /projects/afffd160-11c4-4b0e-8185-cf29c729cf98/miniconda3/envs/ds_env/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[?1l[?2004h[?25l[0m[?7l[0m[J[0;38;5;28mIn [[0;38;5;46;1m24[0;38;5;28m]: [0m                                                                                                                           [132C [9C[?7h[0m[?12l[?25h[9D[J[0m[?7h[?2004l[2J[0;0H[?2004h[?25l[0m[?7l[0m[J[0;38;5;28mIn [[0;38;5;46;1m24[0;38;5;28m]: [0m                                                                                                                           [132C [9C[?7h[0m[?12l[?25h